version: "3.9"

services:
  api:
    build: .
    container_name: phishing_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_phishing
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: phishing_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
